### ISSUE TITLE
Unexpected EOF (End of file).

### ISSUE THREAD

**Issue by ZZHHAANNGG** [scribd/Weaver#53] opened 2018-07-21 18:19 UTC
I have tried several times to re-type a file that weaver compliant about. But, there is still an unexpected EOF (End of file) error. All the files have been corrected by Swiftlint.

How should I check the invalid characters?

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/12008247/43038943-021d8278-8cf1-11e8-8e78-241ec112bb33.png">

**Comment by trupin** [comment] 2018-07-23 15:08
Hi @ZZHHAANNGG,

Thanks for filing this.

Could you give me the complete file which provokes the issue so I can reproduce on my machine?

**Comment by trupin** [comment] 2018-08-01 16:10
Hi @ZZHHAANNGG,

I'm sorry, a lot happened lately, and I didn't have time to look into this bug yet. I'll try give it a look tonight.

**Comment by ZZHHAANNGG** [comment] 2018-08-02 00:46
Hi @trupin 

I sent you an email about the whole project.

**Comment by trupin** [comment] 2018-08-03 16:30
I tried the project you sent me. The Weaver build phase isn't quite right. The output path isn't a valid directory, and the input paths weren't valid either. 

I tried to compile the project with the following build phase instead and it worked with Weaver 0.10.0.

```bash
weaver --output_path ${SOURCE_ROOT}/Classes `find ${SOURCE_ROOT}/Classes/Modules/ -name '*.swift' | xargs -0`
```

Could you try that and tell me if this works for you please?

**Comment by trupin** [comment] 2018-08-03 16:43
Ah now I see an issue when trying with this build phase:

```bash
weaver --output_path ${SOURCE_ROOT}/Classes `find ${SOURCE_ROOT}/songshuixia -name '*.swift' | xargs -0`
```

It seems to include files containing characters that are not handled properly by Weaver. I'm looking into this now.

**Comment by trupin** [comment] 2018-08-03 17:29
@ZZHHAANNGG, I think the bug is fixed with #57. I have been trying to declare dependencies in your project, and everything seems to be functional.

I'm going to merge this and close this ticket. Don't hesitate to reopen it if you run into this issue again.

**Comment by trupin** [comment] 2018-08-07 03:15
Hey @ZZHHAANNGG,

This issue is actually bigger than I thought. I'm currently working on it. I'll let you know when I come up with a fix.

**Comment by trupin** [comment] 2018-08-07 05:02
@ZZHHAANNGG, I think I fixed the issue.

Could you please try with the following binary? [weaver-0.10.1.zip](https://github.com/scribd/Weaver/files/2265032/weaver-0.10.1.zip)

**Comment by ZZHHAANNGG** [comment] 2018-08-08 02:40
@trupin  It works! I am so glad this library is so helpful! Thanks

**Closed** 2018-08-08 02:41 UTC
Labels: bug
